spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/coupangclone?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: coupangclone
    password: coupangclone

  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"

    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=